# Generated by Django 3.2 on 2021-08-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210401_1953'),
        ('accounts', '0002_auto_20210418_0154'),
    ]

    operations = [
    ]
