# Generated by Django 3.1.7 on 2021-03-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
