# Generated by Django 3.2 on 2021-04-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='paidto_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
